[tools.python]
min_version = "3.8.0"
preferred_version = "3.12.0"
check_pip = true

[tools.git]
min_version = "2.20.0"
check_config = true  # Validates user.name/email

[tools.cmake]
min_version = "3.16.0"
portable_install = true  # Enable DevCheck's portable install

[tools.cpp_compiler]
min_standard = "c++17"
# OS-specific preferences
[tools.cpp_compiler.windows]
prefer_msvc = true
[tools.cpp_compiler.linux]
prefer_gcc = true

[devcheck]
default_timeout = 300
auto_install_tools = true
require_user_confirmation = true